services:
  app:
    image: simpsons-quotes-api-dev:latest
    build:
      target: development
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      PHP_IDE_CONFIG: serverName=simpsons-quotes-api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - sh
      - -lc
      - php artisan migrate --seed --force && php artisan serve --host=0.0.0.0 --port=8080
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: .
        target: /var/www/html
        consistency: consistent
      - type: volume
        target: /var/www/html/vendor
